server:
  port: 8090
spring:
  profiles.active: prod
---
spring:
  profiles: licenta
  jpa:
    hibernate:
      ddl-auto: validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/input?useSSL=false
    username: root
#    password: OyhVmhNz6h3zlgKQ
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
---
spring:
  profiles: prod
spring.profiles.include: licenta